language: node_js
node_js:
  - "20"

# 캐싱 설정 → 빌드 속도 향상
cache:
  directories:
    - node_modules

# 의존성 설치
install:
  - npm install

# 빌드 및 테스트 수행
script:
  - npm run build
  - npm test

# 배포 설정
deploy:
  provider: s3
  access_key_id: minachoi
  secret_access_key: AKIAVVJ3VHPI43F4PXL6
  bucket: travis-test-react
  skip_cleanup: true
  local_dir: build
  acl: public_read
  on:
    branch: main
